### PR TITLE
Fix `Modal.stories.tsx` code documentation

### PR DESCRIPTION
**Pull request by nkokla**
Fix typo on `Modal`component code description.

### CODE REVIEW

**Comment by garronej** [comment]
Great thanks!

**Comment by nkokla** [comment]
I found another error. 
I convert to a draft and correct it before sending it back.

**Comment by garronej** [comment]
Great thanks,  
By the way. I'm not very happy of the modal component. It's not done.  We should be able to open and close the modal programmatically, we only provideo a way to open it when a boutton is clicked wich isn't great.

**Comment by nkokla** [comment]
Yes I see that. 🤷‍♂️
After fixing this document error, do you want I send a proposal? 😊

**Comment by garronej** [comment]
Yes, I'd love it.  
Be aware though that the vetting process can be slow.  
There is often a lot of back and forth before the component make it in the codebase.  
Aslo whenever possible, we try to make RSC ready component (See [Server Component](https://beta.nextjs.org/docs/rendering/server-and-client-components)).  
When it's not possible we add a "use client"; header.

**Comment by nkokla** [comment]
I don't understand why the `ci/test_format` failed. 
An idea ?

**Comment by garronej** [comment]
Just run `yarn format` it'll fix it.  
There is a pre commit hooks that runs it automatically...

**Comment by nkokla** [comment]
Exactly, the `yarn format` appear to be OK. (No errors or modification into the code)
This is the cause why i don't understand. 🤷‍♂️

**Comment by garronej** [comment]
Hum, yes indeed, very strange.

**Comment by garronej** [comment]
It's so strange.  
I don't understand what's going on. 
I checked out your branch and indeed when I run `yarn format`, no changes and `yarn format:check` exits with `0` (sucess) but for some reason in the CI in fails.  

Well, whatever, don't worry about it, I'll fore merge.

**Comment by garronej** [comment]
Thank you!

**Pull request merged**
