### PR TITLE
fix: set Submenu items as optional

### PR DESCRIPTION
**Pull request by damienguezou**
Hello,

A little fix of a type. The submenu items should be optional

### CODE REVIEW

**Comment by garronej** [comment]
Hi @damienguezou,  

Thanks for your contribution.  
  
> The submenu items should be optional  

Does it though? I don't see it.

**Comment by damienguezou** [comment]
I think, for direct access : the first case of this page : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/menu-lateral and in the [storybook](https://react-dsfr-components.etalab.studio/?path=/docs/components-sidemenu--default) the first example show a menu without submenu items, but when I try it, there is a typescript issue

There is no submenu, so if I am not wrong it should be optional or maybe I miss something

**Comment by damienguezou** [comment]
Oh yes, didn't see that. My bad

Thanks

**Comment by garronej** [comment]
Don't mention it, types can be confusing.  
Thanks for reporting!

**Comment by garronej** [comment]
Hey @damienguezou, sorry took me a wile to fix all the errors in this components... but the fix should be released in a few minutes.

**Pull request closed without merging**
