### PR TITLE
Feature/select with options prop

### PR DESCRIPTION
**Pull request by garronej**
Hi @enguerranws,

Follow up (yet again) of #76.  
I merget but I rebased again, I spent another hour or so testing and improving the documentation and I realized that there is still quite a lot of work on this.  
Curently there are a lot of way the component can be used that will led to inconsistent state.  
There's also some undocumented behaviour.  
Plus we haven't writen any tests to make sure users don't get red squigly lines when integrating with form libaries.  

The curent implementation (on main) dosen't provide any typesafety but at least it makes it clear to the user that it's  just a wrapper arount a default `<select />`.  
With this branch, we give a false sense of security witch is worse.  

This PR has potential to improve things but it needs more work. I'd say at least 2hours, maybe more.  

Let's schedule another peer programing session.

### CODE REVIEW

**Comment by garronej** [comment]
image
Getting this when using in the regular "controlled no default mode"

**Comment by garronej** [comment]
No action required, We'll se next peer prog session, I just leave the screenshot here as a reminder.

**Comment by enguerranws** [comment]
Oh, I think it's caused by the placeholder, WE should use an empty string as a value if there's a placeholder instead of setting selected prop

**Comment by garronej** [comment]
I'm using a local copy of the component in the SILL so that I can battle proff it before the release:  
https://sill-preprod.lab.sspcloud.fr/list  

https://github.com/codegouvfr/sill-web/blob/main/src/ui/shared/SelectNext.tsx

**Comment by garronej** [comment]
The more I use the new Select the more I like it.  
We shoudld document the very commun usecase where we are creating a select for for a typed list of entry but the selection can be undefined.  

image  


image

**Comment by garronej** [comment]
When there is an empty string value like 
image

We shouldn't see this:  

image

It should be "Toutes"

**Comment by garronej** [comment]
I merge as SelectNext since this select is already much better that the current one but we should schedule a session to finish it.

**Pull request merged**
