### PR TITLE
feat: Add password functional block

### PR DESCRIPTION
**Pull request by damienguezou**
Implémentation of the password functional block : https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles-et-blocs-fonctionnels/demande-de-mot-de-passe

Not sure about the typing of the props. I based them from the InputProps but not sure that was a good idea. Let met know if you think it's better to have an independent typing, I will do the change.

The pre-commit hook   change the export on the package.json and not sure how it's works. I let the package.json on the pull request but let me know if I have to do something. It doesn't add the PasswordInput in the list but I think it's because I put it under a "blocks" folder. Same, let me know if I have to  move the component or change something

### CODE REVIEW

**Comment by enguerranws** [comment]
Not sure that we should implements functional blocks of the DSFR?

**Comment by garronej** [comment]
@enguerranws Yes I think it does serve a purpose.  

@damienguezou @enguerranws  @gary-van-woerkens I've done this PR in video. (You can watch it in x2)  
https://youtu.be/RI6jEPvgKJ4

**Comment by damienguezou** [comment]
@garronej Thanks for the review, I will takes notes for futur contribution

**Comment by garronej** [comment]
https://user-images.githubusercontent.com/6702424/233513324-8754bcbf-da66-48c8-b8e2-136fab3e6586.mov

Maybe we should make so that the label is not positionned because when the info appear it push the content bellow

**Pull request merged**
