### PR TITLE
feat: adding keyboard navigation to Tabs component for accessibility …

### PR DESCRIPTION
**Pull request by BrianRid**
Hello team,   

A small addition to the Tab component in order to activate keyboard navigation to fit accessibility requirements.  

I applied a similar logic from this file : https://github.com/GouvernementFR/dsfr/blob/main/src/component/tab/script/tab/tabs-group.js

Hope this will meet the standards

### CODE REVIEW

**Comment by B2o5T** [comment]
@garronej any thought to migrate to unstyled radix tabs https://www.radix-ui.com/primitives/docs/components/tabs ? instead of implementing manual a11y

**Comment by garronej** [comment]
Thank you for this!  

So sorry I didn't merge it earlyer!

**Comment by garronej** [comment]
> @garronej any thought to migrate to unstyled radix tabs https://www.radix-ui.com/primitives/docs/components/tabs ? instead of implementing manual a11y  

We can't introduce any thrird party dependency to the core components. This project is a compatibility layer for https://github.com/GouvernementFR/dsfr

**Comment by garronej** [comment]
Sure sorry

**Pull request merged**
